# REMOVA a linha version: (ela é obsoleta)

volumes:
  prometheus_data: {}
  grafana_data: {}
  postgres_data: {}
  redis_data: {}
  loki_data: {}
  node_red_data: {}

networks:
  zecobranca_network:
    driver: bridge

services:
  zecobranca_db:
    image: postgres:15-alpine
    container_name: zecobranca_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zecobranca
      POSTGRES_PASSWORD: zecobranca
      POSTGRES_DB: zecobranca
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zecobranca_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zecobranca -d zecobranca"]
      interval: 10s
      timeout: 5s
      retries: 5

  zecobranca_redis:
    image: redis:7-alpine
    container_name: zecobranca_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - zecobranca_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SOLUÇÃO PARA O CHATBOT - construindo localmente
  zecobranca_chatbot:
    build:
      context: .  # Ajuste este caminho para onde está seu Dockerfile
      dockerfile: Dockerfile
    container_name: zecobranca_chatbot
    restart: unless-stopped
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgresql://zecobranca:zecobranca@zecobranca_db:5432/zecobranca
      REDIS_URL: redis://zecobranca_redis:6379
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here_change_me}
    ports:
      - "3000:3000"
    depends_on:
      zecobranca_db:
        condition: service_healthy
      zecobranca_redis:
        condition: service_healthy
    networks:
      - zecobranca_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  zecobranca_prometheus:
    image: prom/prometheus:latest
    container_name: zecobranca_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - zecobranca_network
    depends_on:
      - zecobranca_chatbot

  zecobranca_grafana:
    image: grafana/grafana:latest
    container_name: zecobranca_grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - zecobranca_network
    depends_on:
      - zecobranca_prometheus

  zecobranca_loki:
    image: grafana/loki:latest
    container_name: zecobranca_loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - zecobranca_network

  zecobranca_promtail:
    image: grafana/promtail:latest
    container_name: zecobranca_promtail
    restart: unless-stopped
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - zecobranca_network
    depends_on:
      - zecobranca_loki

  zecobranca_node_red:
    image: nodered/node-red:latest
    container_name: zecobranca_node_red
    restart: unless-stopped
    environment:
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_USERNAME: ${NODE_RED_USERNAME:-admin}
      NODE_RED_PASSWORD: ${NODE_RED_PASSWORD:-admin}
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    networks:
      - zecobranca_network
    depends_on:
      - zecobranca_chatbot
